"""add public monitoring geographic fields

Revision ID: 1c14be9007e8
Revises: d21a9f4d3d32
Create Date: 2026-08-02 11:23:42.967318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c14be9007e8'
down_revision = 'd21a9f4d3d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city_regency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('needs_geographic_resolution', sa.Boolean(), nullable=True))

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city_regency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('maps_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('business_review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('needs_geographic_resolution', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_reply_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('owner_reply_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('source_url')
        batch_op.drop_column('owner_reply_date')
        batch_op.drop_column('owner_reply_text')

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('needs_geographic_resolution')
        batch_op.drop_column('source')
        batch_op.drop_column('business_review_count')
        batch_op.drop_column('business_rating')
        batch_op.drop_column('maps_url')
        batch_op.drop_column('district')
        batch_op.drop_column('city_regency')
        batch_op.drop_column('province')

    with op.batch_alter_table('location_candidates', schema=None) as batch_op:
        batch_op.drop_column('needs_geographic_resolution')
        batch_op.drop_column('district')
        batch_op.drop_column('city_regency')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
