"""add city and trial_ends_at to Business

Revision ID: 373f72bb0e40
Revises: 1c14be9007e8
Create Date: 2026-08-03 22:40:36.112833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373f72bb0e40'
down_revision = '1c14be9007e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
