"""initial schema

Revision ID: 9996ce1537a6
Revises: 
Create Date: 2026-07-29 11:48:51.046519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9996ce1537a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('pubsub_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('google_account_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('review_name', sa.String(length=500), nullable=True),
    sa.Column('location_name', sa.String(length=500), nullable=True),
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_account_id', 'message_id', name='uq_pubsub_message')
    )
    with op.batch_alter_table('pubsub_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pubsub_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_valid', sa.Integer(), nullable=True),
    sa.Column('rows_invalid', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_report_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('location_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('place_id', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('google_maps_uri', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('discovery_status', sa.String(length=50), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('owner_verification_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'place_id', name='uq_candidate_place')
    )
    with op.batch_alter_table('location_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_candidates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outlets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('public_place_id', sa.String(length=200), nullable=True),
    sa.Column('gbp_account_id', sa.String(length=200), nullable=True),
    sa.Column('gbp_location_id', sa.String(length=200), nullable=True),
    sa.Column('owner_verification_status', sa.String(length=50), nullable=True),
    sa.Column('gbp_match_status', sa.String(length=50), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), nullable=True),
    sa.Column('reply_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'gbp_location_id', name='uq_outlet_gbp_location')
    )
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('google_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('google_subject_id', sa.String(length=200), nullable=True),
    sa.Column('selected_account_id', sa.String(length=200), nullable=True),
    sa.Column('encrypted_access_token_ref', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token_ref', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('connected_by', sa.String(length=36), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_connections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_review_name', sa.String(length=500), nullable=True),
    sa.Column('review_id', sa.String(length=200), nullable=True),
    sa.Column('reviewer_display_name', sa.String(length=200), nullable=True),
    sa.Column('reviewer_is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('has_text', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_visibility_status', sa.String(length=50), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_review_name', name='uq_review_source')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=True),
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('pattern_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('reputation_risk', sa.String(length=20), nullable=True),
    sa.Column('source_facts', sa.JSON(), nullable=True),
    sa.Column('ai_assessment', sa.JSON(), nullable=True),
    sa.Column('primary_owner_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('supporting_roles', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_checklist', sa.JSON(), nullable=True),
    sa.Column('internal_notes', sa.JSON(), nullable=True),
    sa.Column('evidence_attachments', sa.JSON(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('review_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_pk', sa.String(length=36), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('reputation_risk', sa.String(length=20), nullable=True),
    sa.Column('repeat_pattern_candidate', sa.Boolean(), nullable=True),
    sa.Column('responsible_role', sa.String(length=50), nullable=True),
    sa.Column('recommended_public_response_intent_json', sa.JSON(), nullable=True),
    sa.Column('recommended_internal_action_json', sa.JSON(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('confidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_pk'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_pk', sa.String(length=36), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_text', sa.Text(), nullable=True),
    sa.Column('publication_status', sa.String(length=50), nullable=True),
    sa.Column('google_reply_update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reply_state', sa.String(length=50), nullable=True),
    sa.Column('policy_violation', sa.Text(), nullable=True),
    sa.Column('review_reply_url', sa.Text(), nullable=True),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_pk'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_pk', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source_update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_pk'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('review_reply_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_reply_id'], ['review_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_tenant_id'))

    op.drop_table('approvals')
    op.drop_table('review_versions')
    op.drop_table('review_replies')
    op.drop_table('review_analyses')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_tenant_id'))

    op.drop_table('issues')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_tenant_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_connections_tenant_id'))

    op.drop_table('google_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlets_tenant_id'))

    op.drop_table('outlets')
    with op.batch_alter_table('location_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_candidates_tenant_id'))

    op.drop_table('location_candidates')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_tenant_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('pubsub_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pubsub_events_tenant_id'))

    op.drop_table('pubsub_events')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_tenant_id'))

    op.drop_table('businesses')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
