"""feat: add oauth_state, mock columns

Revision ID: b2530f489e05
Revises: 9996ce1537a6
Create Date: 2026-07-29 14:58:47.823310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2530f489e05'
down_revision = '9996ce1537a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nonce_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_intent', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_nonce_hash'), ['nonce_hash'], unique=True)

    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('adapter_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.drop_column('adapter_mode')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('last_error')

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_nonce_hash'))

    op.drop_table('oauth_states')
    # ### end Alembic commands ###
