"""feat: add review_raw_payloads, sync_reports, run04 columns

Revision ID: cd11cd29cadf
Revises: b2530f489e05
Create Date: 2026-07-29 17:18:29.871074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd11cd29cadf'
down_revision = 'b2530f489e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('locations_requested', sa.Integer(), nullable=True),
    sa.Column('locations_succeeded', sa.Integer(), nullable=True),
    sa.Column('locations_failed', sa.Integer(), nullable=True),
    sa.Column('reviews_received', sa.Integer(), nullable=True),
    sa.Column('reviews_created', sa.Integer(), nullable=True),
    sa.Column('reviews_updated', sa.Integer(), nullable=True),
    sa.Column('reviews_unchanged', sa.Integer(), nullable=True),
    sa.Column('rating_only_reviews', sa.Integer(), nullable=True),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=True),
    sa.Column('analysis_jobs_created', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('review_raw_payloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('review_pk', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_account_id', sa.String(length=200), nullable=True),
    sa.Column('source_location_id', sa.String(length=200), nullable=True),
    sa.Column('source_review_name', sa.String(length=500), nullable=True),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['review_pk'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_raw_payloads_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_raw_payloads_raw_payload_hash'), ['raw_payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_raw_payloads_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_api_connected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('review_endpoint_accessible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reply_capability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('blocking_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualitative_analysis_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('review_updated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('analysis_reassessment_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('analysis_reassessment_required')
        batch_op.drop_column('review_updated')
        batch_op.drop_column('qualitative_analysis_status')

    with op.batch_alter_table('google_connections', schema=None) as batch_op:
        batch_op.drop_column('blocking_reason')
        batch_op.drop_column('reply_capability')
        batch_op.drop_column('review_endpoint_accessible')
        batch_op.drop_column('production_api_connected')

    with op.batch_alter_table('review_raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_raw_payloads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_review_raw_payloads_raw_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_review_raw_payloads_business_id'))

    op.drop_table('review_raw_payloads')
    with op.batch_alter_table('sync_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_reports_tenant_id'))

    op.drop_table('sync_reports')
    # ### end Alembic commands ###
