"""added closed_by closed_at IssuePattern PatternReview

Revision ID: d21a9f4d3d32
Revises: cd11cd29cadf
Create Date: 2026-07-30 13:58:26.913777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21a9f4d3d32'
down_revision = 'cd11cd29cadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('parent_issue_id', sa.String(length=36), nullable=True),
    sa.Column('pattern_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('outlet_specific', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['parent_issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_patterns_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pattern_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['issue_patterns.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', 'review_id', name='uq_pattern_review')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['closed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('closed_by')

    op.drop_table('pattern_reviews')
    with op.batch_alter_table('issue_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_patterns_tenant_id'))

    op.drop_table('issue_patterns')
    # ### end Alembic commands ###
